import pyttsx3 as tts
engine = tts.init()

def speed(number):
    rate = engine.getProperty('rate')
    engine.setProperty('rate', number)
    print(f"Talking speed set to: {number}")

def voice(integer):
    voices = engine.getProperty('voices')
    engine.setProperty('voice', voices[integer].id)
    print(f"Voice set to: {integer}")

def talk(text):
    engine.say(text)
    engine.runAndWait()

def save(text, name):
    engine.save_to_file(text, name+".mp3")
    engine.runAndWait()
    print("Saved")

speed(200)
voice(0)
talk("This audio was generated by Python!")
save("This audio was generated by Python!", "audio")